language: node_js

node_js:
  - "7.3.0"

os:
  - linux

env:
  - PATH=$PATH:/home/travis/.nvm/versions/node/v7.3.0/bin/

sudo: required

dist: wheezy

install:
  - sudo apt-get -y install perl
  - npm install

script:
  - npm test
