language: node_js

os:
  - linux

sudo: required

dist: trusty

node_js:
  - "6"
  - "node"

install:
  - sudo apt-get -y install perl
  - npm install

script:
- npm test

notifications:
  email: true
