language: node_js

node_js:
  - stable

os:
  - linux

sudo: required

dist: trusty

install:
  - sudo apt-get -y install perl
  - sudo apt-get -y install npm
  - npm install

script:
  - npm test

notifications:
  email: false
