language: node_js

node_js:
  - stable

os:
  - linux

env:
  - PATH=/usr/bin

sudo: required

dist: trusty

install:
  - sudo apt-get -y install perl
  - npm install

script:
  - npm test

notifications:
  email: false
